/*
-- Query: SELECT * FROM product
LIMIT 0, 1000

-- Date: 2025-10-05 13:49
*/
INSERT INTO `` (`id`,`description`,`image_url`,`name`,`price`,`stock`,`category_id`) VALUES (1,'Latest model smartphone with 128GB storage','https://www.washingtonpost.com/wp-apps/imrs.php?src=https://arc-anglerfish-washpost-prod-washpost.s3.amazonaws.com/public/GII3ERO4CJNI4WSMB2QYHVSOUM.jpg&w=1440&impolicy=high_res','Smartphone X',125000,50,1);
INSERT INTO `` (`id`,`description`,`image_url`,`name`,`price`,`stock`,`category_id`) VALUES (2,'High-performance gaming laptop with 16GB RAM','https://jarrods.tech/wp-content/uploads/2023/12/asus-rog-zephyrus-m16-2023-gaming-laptop-1536x864.jpg','Gaming Laptop Pro',180000,30,1);
INSERT INTO `` (`id`,`description`,`image_url`,`name`,`price`,`stock`,`category_id`) VALUES (3,'Wireless noise-cancelling headphones','https://5.imimg.com/data5/ANDROID/Default/2025/5/507336670/WR/PT/JV/18726985/product-jpeg-1000x1000.jpg','Noise-Cancelling Headphones',2500,80,1);
INSERT INTO `` (`id`,`description`,`image_url`,`name`,`price`,`stock`,`category_id`) VALUES (4,'Smartwatch with health tracking features','https://images-cdn.ubuy.ae/66023f3cc4fde233421eb9bc-new-smart-watch-call-receive-dial-hd.jpg','Smartwatch 2.0',3200,40,1);
INSERT INTO `` (`id`,`description`,`image_url`,`name`,`price`,`stock`,`category_id`) VALUES (5,'Cotton T-shirt available in multiple colors','https://2.wlimg.com/product_images/bc-full/2025/9/5739790/mullty-colors-t-shirts-1756707471-8302577.jpg','Classic T-Shirt',800,150,2);
INSERT INTO `` (`id`,`description`,`image_url`,`name`,`price`,`stock`,`category_id`) VALUES (6,'Comfortable denim jeans','https://jimmyluxury.in/cdn/shop/files/IMG_7020.jpg?v=1749016690','Denim Jeans',1349,100,2);
INSERT INTO `` (`id`,`description`,`image_url`,`name`,`price`,`stock`,`category_id`) VALUES (7,'Stylish hoodie for casual wear','https://images.meesho.com/images/products/443463999/v0tae_512.webp?width=512','Casual Hoodie',5299,120,2);
INSERT INTO `` (`id`,`description`,`image_url`,`name`,`price`,`stock`,`category_id`) VALUES (8,'Bestselling thriller novel','https://assets.visme.co/templates/banners/thumbnails/i_Thriller-Book-Cover_full.jpg','The Mystery Novel',499,200,3);
INSERT INTO `` (`id`,`description`,`image_url`,`name`,`price`,`stock`,`category_id`) VALUES (9,'Learn Java programming from scratch','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS6IKZ0R1TLE7WG2XSJeleT9zwxfuI5S8XYfA&s','Java Programming Guide',899,100,3);
INSERT INTO `` (`id`,`description`,`image_url`,`name`,`price`,`stock`,`category_id`) VALUES (10,'Inspirational self-help book','https://d1csarkz8obe9u.cloudfront.net/posterpreviews/motivational-self-help-book-cover-design-template-549362a7c9d568279e866eb81510239c_screen.jpg?ts=1731915633','Motivation 101',349,150,3);
INSERT INTO `` (`id`,`description`,`image_url`,`name`,`price`,`stock`,`category_id`) VALUES (21,'Compact and lightweight 5-in-1 travel adapter with multiple port types for global use','https://www.boat-lifestyle.com/cdn/shop/files/Artboard1_2c6b6009-e78d-4ab3-8693-7f86d90b7f27_1800x.png?v=1755156004','5-in-1 Travel Adapter',2800,150,5);
INSERT INTO `` (`id`,`description`,`image_url`,`name`,`price`,`stock`,`category_id`) VALUES (22,'Ergonomic Bluetooth wireless keyboard with rechargeable battery and slim design','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR1b0dEVOD0wyX5ilz991Riba96Whbah20Nqg&s','Bluetooth Wireless Keyboard',2400,80,6);
INSERT INTO `` (`id`,`description`,`image_url`,`name`,`price`,`stock`,`category_id`) VALUES (23,'Beginner acoustic guitar with spruce top and mahogany back and sides, natural finish','https://www.pratleyguitars.com.au/cdn/shop/files/STC-SE-RWS1.jpg?v=1717213298','Acoustic Guitar Starter Pack',8000,40,7);
INSERT INTO `` (`id`,`description`,`image_url`,`name`,`price`,`stock`,`category_id`) VALUES (24,'Lightweight, water-resistant travel backpack with multiple compartments and USB charging port','https://travelfreak.com/wp-content/uploads/2021/10/best-travel-backpack-women.jpg','Travel Backpack with USB Port',7500,70,5);
INSERT INTO `` (`id`,`description`,`image_url`,`name`,`price`,`stock`,`category_id`) VALUES (25,'Set of 12 gel ink pens with smooth writing and quick-drying ink, assorted colors','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTqWuhtn8FwY3kwDq2m5skiuulPOOr3aKRx0A&s','Assorted Gel Ink Pens - 12 Pack',350,130,6);
INSERT INTO `` (`id`,`description`,`image_url`,`name`,`price`,`stock`,`category_id`) VALUES (26,'Electric keyboard with 61 keys, multiple tones, and built-in speakers for beginners','https://images.unsplash.com/photo-1570698824041-22cbab696486?fm=jpg&q=60&w=3000&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxzZWFyY2h8M3x8a2V5Ym9hcmQlMjBpbnN0cnVtZW50fGVufDB8fDB8fHww','61-Key Electric Keyboard',9899,30,7);
INSERT INTO `` (`id`,`description`,`image_url`,`name`,`price`,`stock`,`category_id`) VALUES (27,'Compact and ultra-lightweight packable daypack, perfect for day trips and hikes','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQvCVGgdEHvZrYWogGEKIkiR_i4JWske7v8Lw&s','Packable Daypack',2890,85,5);
INSERT INTO `` (`id`,`description`,`image_url`,`name`,`price`,`stock`,`category_id`) VALUES (28,'Portable travel-size electric toothbrush with long battery life and charging case','https://m.media-amazon.com/images/I/71IEhotxOrS.jpg','Portable Electric Toothbrush',1599,65,5);
INSERT INTO `` (`id`,`description`,`image_url`,`name`,`price`,`stock`,`category_id`) VALUES (29,'Digital luggage scale with a backlit display for accurate weight measurement up to 50kg','https://m.media-amazon.com/images/I/71Gd6eacBSL.jpg','Digital Luggage Scale',5799,120,5);
INSERT INTO `` (`id`,`description`,`image_url`,`name`,`price`,`stock`,`category_id`) VALUES (30,'Multi-functional stapler with anti-jam mechanism and ergonomic design','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcGpjvoIzW6YZGjMkuPiYKwBcXijJOeoFroQ&s','Ergonomic Stapler',1399,150,6);
INSERT INTO `` (`id`,`description`,`image_url`,`name`,`price`,`stock`,`category_id`) VALUES (31,'Set of 5 durable file folders with color-coded tabs for easy organization','https://cdn.grofers.com/cdn-cgi/image/f=auto,fit=scale-down,q=70,metadata=none,w=1080/da/cms-assets/cms/product/9232885d-385e-4290-9a4d-1f6ca957b633.jpg','Color-coded File Folders',359,200,6);
INSERT INTO `` (`id`,`description`,`image_url`,`name`,`price`,`stock`,`category_id`) VALUES (32,'Adjustable desk lamp with LED light and touch control','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR44reNMD09sc6qDNKF1vkduTD7MsZsYb1Ize7pHx6eGU63iCLzPRyvjBzCd2NAsHe7nSg&usqp=CAU','LED Desk Lamp',1200,75,6);
INSERT INTO `` (`id`,`description`,`image_url`,`name`,`price`,`stock`,`category_id`) VALUES (33,'38 inch cutaway acoustic guitar with gig bag, strap, picks, and string set included','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHJCy7_tMLbeq_X2haxyxIGvmDA7SvXXGopg&s','Henrix 38C Acoustic Guitar',1499,50,7);
INSERT INTO `` (`id`,`description`,`image_url`,`name`,`price`,`stock`,`category_id`) VALUES (34,'88 key digital piano with weighted keys and built-in speakers, suitable for beginners','https://cdn.korg.com/us/products/upload/510e7b6c283c682da323b4bcc15223cf.jpg','Yamaha P145 Digital Piano',36599,25,7);
INSERT INTO `` (`id`,`description`,`image_url`,`name`,`price`,`stock`,`category_id`) VALUES (35,'7-piece electronic drum kit featuring mesh heads and Bluetooth connectivity','https://i.pinimg.com/736x/f9/f6/e2/f9f6e2fe6b29905fb49f77b999f7b387.jpg','Alesis Nitro Max Drum Kit',40890,15,7);
INSERT INTO `` (`id`,`description`,`image_url`,`name`,`price`,`stock`,`category_id`) VALUES (36,'Premium electric guitar with solid body, dual pickups, and chrome hardware','https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQwTlXTW8_1Mrv-gOTjTrrws4xQqQTUD_iTrg&s','Fender Player Stratocaster',68999,20,7);
